### ISSUE TITLE
Cardboard under the sound board

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#1]
There is an air intake under the board that is blocked by the foam.
There was some cardboard under there that seems to have gone missing.

**Comment by michellestith** [comment]
I have the box from the new board; will see if the cardboard is still there.

**Comment by russell-taylor** [comment]
Mark Stith is redoing the lid and Michelle is looking into putting a board under the sound board. We might also be able to scrape of the foam padding and leave the sound board on the shelf

**Comment by damiancmunn** [comment]
I wouldn't think the foam is necessary with new board, I would still recommend either a cloth or cardboard surface under both boards as you can still hear the fan run (at PBO) because of the sound reflective surface of the PBO cart. The chipboard that the Woods cart is comprised of may not be as bad.

**Comment by russell-taylor** [comment]
Michelle, reminder to bring this tomorrow.
