### ISSUE TITLE
Cloth in front of Pittsboro sound board

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#14]
To cover the stuff sitting in there

**Comment by russell-taylor** [comment]
39 3/4 inches across
22 1/2 inches from top of top board to top of bottom board, 27 is still above the floor

**Comment by michellestith** [comment]
Thanks, Russ

Let's hold off on any forum discussion about issues at the PBO space for
now.The punch A/V list for the worship space at PBO is still quite long,
but we made the decision to wait until after Easter to complete the
installation, since everything is working well right now.  I anticipate
considering the job 'completed' by mid-May.

The organizer and cover of some sort are on the list, as well as shortening
the cabling in there, etc
~m
