### ISSUE TITLE
Pastor wireless interference at Pittsboro

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#27]
We had fuzz three times during the sermon. The rf signal dropped halfway during these. After the service we checked and there was no interference. Moving the antenna on the belt pack did not help. It looks like there is a device being brought in that is operating on the frequencies we are using. 

This will probably also happen at woods. It will probably get worse as more of these devices appear.

**Comment by michellestith** [comment]
In discussion with the sweetwater rep.  I got this one.

**Comment by russell-taylor** [comment]
Tried adjusting the bank and channel to try and find a better one after the service today but there was the same amount of interference across them.

**Comment by michellestith** [comment]
Purchased a new receiver/transmitter set.  Installed in the soundboard in hopes the issue was outdated bandwidth or degraded equipment.  Unfortunately the problem persisted.  Moved the receiver to the stage, installed in channel 14. updated to Ch 14 on the board as well.  We'll see if that solves the problem

**Comment by russell-taylor** [comment]
Thanks for taking care of this!  Moving the receiver seems to have solved the problem.  If you agree, go ahead and close the issue.
