### ISSUE TITLE
Buy power cords for monitors for pbo

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#45]
Like 3 or 4

**Comment by michellestith** [comment]
There should be some in the "monitor" box in the av closet.(smallish, clear
box I think)  Are they broken or missing?

**Comment by russell-taylor** [comment]
Didn't notice that. Will check before buying.

**Comment by russell-taylor** [comment]
I checked all of the boxes in there including the clear ones. Didn't see any labeled ones and found no power cords.

**Comment by michellestith** [comment]
Well, each one comes with a power cord, and we only need to use the in
between one.  So it would surprise me that that many went missing.  I am
almost past my prohibition against driving and can probably take a look on
Friday.

**Comment by michellestith** [comment]
Hi Russ,
I found three power cords for the personal mixers in the personal mixer box
(not labeled) in the a/v closet.  I put the power cords on the a/v rack
behind stage.  Let me know if you need anything else.
-m

**Comment by russell-taylor** [comment]
We were looking for the computer-style power cords for the floor monitors.  We seem to have several more monitors than power cables.

**Comment by michellestith** [comment]
Oh I see.
I'm a little confused here - are we using floor monitors in PBO?
I thought you meant the dc power cords that work on the P16 personal mixer.
Are you talking about the JBL powered speakers we use at Woods on the floor
for the vocalists' monitors?
Either way, it never hurts to have extra "computer" cables since they are
compatible with many devices.  They also have a tendency to go
missing....So please feel free to purchase some of those.
-m

**Comment by russell-taylor** [comment]
We're not using the floor monitors, but whenever we need a power cord we need to steal one from the back room.  Ordered 4 of them from Amazon for delivery on Thursday.  I'll bring to P'boro or Steve Tamayo.

**Comment by russell-taylor** [comment]
Delivered to the wiring rack in Pittsboro.
