### ISSUE TITLE
Printed manual for the Behringer board at Pittsboro

### ISSUE THREAD

**Issue by russell-taylor** [chatham-community-church/Worship#7]
Would be good to print a copy from https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiw8PyzytHSAhUHyyYKHZmaDisQFggcMAA&url=https%3A%2F%2Fmedia.music-group.com%2Fmedia%2FPLM%2Fdata%2Fdocs%2FP0ASF%2FX32_M_EN.pdf&usg=AFQjCNEP2A-Ng2myMqMwel3HWezbtfRhAA&sig2=l14agEYhaLYWqqLGAUqILw or elsewhere and have onsite for people to refer to.

**Comment by russell-taylor** [comment]
Michelle if you want me to print a copy and bring at easter just assign the issue to me.

**Comment by russell-taylor** [comment]
Printing now and planning to bring tomorrow.

**Comment by michellestith** [comment]
Woops sorry russ, I did not understand this email thread (until now)
because I had a printed copy in the a/v room a couple weeks ago.  But now
we have two!  No kidding it might be nice to have one to take home to study
when someone wants to.  Thanks for following up on that and for the
batteries.
-m

**Comment by russell-taylor** [comment]
No worries. Brought the second copy so closing this issue.
